/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jgranados.ipc1_jun_2022.guessanumber.fe;

import com.jgranados.ipc1_jun_2022.guessanumber.be.IA;
import com.jgranados.ipc1_jun_2022.guessanumber.be.Jugador;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class GuessANumberFrame extends javax.swing.JFrame {
    private IA ia;
    private Jugador jugador;
    private Jugador[] jugadores = new Jugador[10];
    private int contadorJugadores = 0;
    
    /**
     * Creates new form GuessANumberFrame
     */
    public GuessANumberFrame() {
        ia = new IA();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        punteoLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        entradaTxt = new javax.swing.JTextField();
        validarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        intentosLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuJugar = new javax.swing.JMenu();
        iniciarJuegoBtn = new javax.swing.JMenuItem();
        verPunteosBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Punteo:");

        jLabel2.setText("Nombre:");

        jLabel5.setText("Adivina el numero...");

        validarBtn.setText("Validar");
        validarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Intentos restantes:");

        menuJugar.setText("Jugar");

        iniciarJuegoBtn.setText("Jugar");
        iniciarJuegoBtn.setToolTipText("");
        iniciarJuegoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJuegoBtnActionPerformed(evt);
            }
        });
        menuJugar.add(iniciarJuegoBtn);

        verPunteosBtn.setText("Ver punteos");
        verPunteosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPunteosBtnActionPerformed(evt);
            }
        });
        menuJugar.add(verPunteosBtn);

        jMenuBar1.add(menuJugar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(punteoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entradaTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(validarBtn)
                                    .addComponent(intentosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(punteoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validarBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(intentosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarJuegoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJuegoBtnActionPerformed
        PedirNombreDialog dialog = new PedirNombreDialog(this);
        dialog.setVisible(true);
        jugador = new Jugador(dialog.darNombre());
        actualizarDatosJugador();
        actualizarIntentos();
        ia.generarNumero();
    }//GEN-LAST:event_iniciarJuegoBtnActionPerformed

    private void validarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarBtnActionPerformed
        int entrada = Integer.parseInt(entradaTxt.getText());
        if (ia.validarEntrada(entrada, jugador)) {
            JOptionPane.showMessageDialog(this, "Adivinaste!! tu punteo es de " + jugador.obtenerPunteo());
            actualizarDatosJugador();
        } else {
            JOptionPane.showMessageDialog(this, "Fallaste!!");
            verificarSiPerdio();
        }
        actualizarIntentos();
    }//GEN-LAST:event_validarBtnActionPerformed

    private void verPunteosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPunteosBtnActionPerformed
        PunteosDialog punteos = new PunteosDialog(this, jugadores);
        punteos.setVisible(true);
    }//GEN-LAST:event_verPunteosBtnActionPerformed

    private void actualizarDatosJugador() {
        punteoLbl.setText("" + jugador.obtenerPunteo());
        nombreLbl.setText(jugador.obtenerNombre());
    }
    
    private void actualizarIntentos() {
        intentosLbl.setText("" + ia.obtenerIntentosRestantes());
    }
    
    private void verificarSiPerdio() {
        if (!ia.sigueConVida()) {
            JOptionPane.showMessageDialog(this, "Ya perdiste!!");
            agregarJugadorAListado();
            limpiarDatosJugador();
        }
    }
    
    private void agregarJugadorAListado() {
        if (contadorJugadores >= 10) {
            contadorJugadores = 0;
        }
        jugadores[contadorJugadores] = jugador;
        contadorJugadores++;
    }
    
    private void limpiarDatosJugador() {
        punteoLbl.setText("");
        nombreLbl.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entradaTxt;
    private javax.swing.JMenuItem iniciarJuegoBtn;
    private javax.swing.JLabel intentosLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menuJugar;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel punteoLbl;
    private javax.swing.JButton validarBtn;
    private javax.swing.JMenuItem verPunteosBtn;
    // End of variables declaration//GEN-END:variables
}
