/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jgranados.ipc1_jun_2022.buscaminas.fe;

import com.jgranados.ipc1_jun_2022.buscaminas.be.partida.Jugador;
import com.jgranados.ipc1_jun_2022.buscaminas.be.partida.Partida;
import com.jgranados.ipc1_jun_2022.buscaminas.be.tablero.Tablero;

/**
 *
 * @author jose
 */
public class BuscaminasFrame extends javax.swing.JFrame {
    
    private Partida partidaEnCurso;
    private Tablero tableroEnUso;

    /**
     * Creates new form BuscaminasFrame
     */
    public BuscaminasFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        turnoLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tableroPnl = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoJuegoBtn = new javax.swing.JMenuItem();
        resultadosBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(423, 564));
        setSize(new java.awt.Dimension(423, 564));

        jLabel1.setText("Turno No.:");

        jLabel2.setText("Jugador en turno:");

        tableroPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableroPnl.setLayout(new java.awt.GridLayout(6, 4, 1, 1));

        jMenu1.setText("Juego");

        nuevoJuegoBtn.setText("Nuevo juego");
        nuevoJuegoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoJuegoBtnActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoJuegoBtn);

        resultadosBtn.setText("Resultados");
        jMenu1.add(resultadosBtn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableroPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(turnoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(turnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableroPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoJuegoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoJuegoBtnActionPerformed
        PedirNombreSDialog pedirNombresDialog = new PedirNombreSDialog(this);
        pedirNombresDialog.setVisible(true);
        Jugador jugadorA = new Jugador(pedirNombresDialog.darNombreA());
        Jugador jugadorB = new Jugador(pedirNombresDialog.darNombreB());
        
        partidaEnCurso = new Partida(jugadorA, jugadorB, this);
        mostrarTablero();
        actualizarDatosJugadores();
        actualizarDatosTurno();
        
    }//GEN-LAST:event_nuevoJuegoBtnActionPerformed

    private void mostrarTablero() {
        for (int i = 0; i < Tablero.FILAS; i++) {
            for (int j = 0; j < Tablero.COLUMNAS; j++) {
                tableroPnl.add(partidaEnCurso.obtenerTableroEnUso().obtenerCasillas()[i][j]);
            }
            
        }
        tableroPnl.validate();
        tableroPnl.repaint();
    }
    
    public void actualizarDatosJugadores() {
        nombreLbl.setText(partidaEnCurso.obtenerJugadorEnTurno().getNombre());
    }
    
    public void actualizarDatosTurno() {
        turnoLbl.setText("" + partidaEnCurso.obtenerTurno());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JMenuItem nuevoJuegoBtn;
    private javax.swing.JMenuItem resultadosBtn;
    private javax.swing.JPanel tableroPnl;
    private javax.swing.JLabel turnoLbl;
    // End of variables declaration//GEN-END:variables
}
